### ISSUE TITLE
Export (backup/update) to a GitHub Gist

### ISSUE THREAD

**Issue by StanleyGoldman** [johnridesabike/coronate#28]
I've seen this used as a tactic in other web applications that use browser storage. The current export is sufficient as is, this is not a requirement at all, but I figured I would mention it in case you hadn't thought of it already.

https://docs.github.com/en/rest/reference/gists

**Comment by johnridesabike** [comment]
This looks interesting. The app would save the data to a gist?

I've thought about adding some kind of "save to the cloud" feature, since browser storage has big limitations. But lack of time has kept me from doing that. If using gists is simple and low-maintenance enough, then I'll definitely look into this.

**Comment by johnridesabike** [comment]
@StanleyGoldman I have a PR with this feature now #29 

It moves the hosting to Netlify (to take advantage of their OAuth service). You can beta test it here: https://608e9526c41e778edda5a03e--coronate.netlify.app/

If everything looks good. I'll merge this soon.

**Comment by StanleyGoldman** [comment]
My bad, I never got a chance to test this... checking it out now..

**Comment by johnridesabike** [comment]
Great!
