### ISSUE TITLE
adjusting K Factor?

### ISSUE THREAD

**Issue by scottf2** [johnridesabike/coronate#39]
First of all, thanks so much for this great software - we just used it to run a casual tournament for the UC Davis Chess club and it worked great.

Is there a way to adjust the K factor for ratings adjustments? I notice it as a field in the Player screen but it is greyed out and not editable, and I can't find any options for it.  

Thanks again.

**Comment by johnridesabike** [comment]
The K factor is automatically calculated, and it's only really displayed for debugging. The exact formula I use is: `800 / number of matches played`. So you can indirectly adjust it by editing a player's number of matches.

Honestly, I didn't put a lot of thought into it after I initially added it. I think I chose the number 800 because, IIRC, that's what USCF uses. So I wouldn't mind updating the feature, but I'm also not sure what the best implementation would be. 

Since it's supposed to automatically change for each player as they play more matches, I'm not sure if manually editing it would make sense. Perhaps there could be an extra field for adding/subtracting from the calculated K-factor?

**Comment by johnridesabike** [comment]
I have an update ready which addresses this. You still can't adjust the K-factor, but I changed how it displays to make it less confusing. I'm not sure if manually adjusting the K-factor would be useful, but I'm happy to consider it if anyone has a use case for it.

You can preview the changes here: https://deploy-preview-40--coronate.netlify.app/
